# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'install_path_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 90)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("*{background: #424242;\n"
"border-radius: 5px;\n"
"border: 1px solid;\n"
"height: 30px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setStyleSheet("*{image: url(:/folder_icon/icons8-folder-24.png);\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 1px solid;\n"
"height: 30px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.select_button.setText("")
        self.select_button.setObjectName("select_button")
        self.horizontalLayout.addWidget(self.select_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setStyleSheet("*{image: url(:/enter_icon/icons8-next-page-24.png);\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 1px solid;\n"
"height: 30px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.apply_button.setText("")
        self.apply_button.setObjectName("apply_button")
        self.verticalLayout.addWidget(self.apply_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter path for app data..."))
import window.interface.resource.src_rc