# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_vocab_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 280)
        MainWindow.setStyleSheet("background:  #323232;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vocabs_list = QtWidgets.QListWidget(self.centralwidget)
        self.vocabs_list.setStyleSheet("*{background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}")
        self.vocabs_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.vocabs_list.setObjectName("vocabs_list")
        self.verticalLayout.addWidget(self.vocabs_list)
        self.vocab_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.vocab_edit.setStyleSheet("*{background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.vocab_edit.setObjectName("vocab_edit")
        self.verticalLayout.addWidget(self.vocab_edit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setStyleSheet("*{image: url(:/delete_icon/icons8-remove-24.png);\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.delete_button.setText("")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setStyleSheet("*{image: url(:/add_icon/icons8-add-24.png);\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.create_button.setText("")
        self.create_button.setObjectName("create_button")
        self.horizontalLayout.addWidget(self.create_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manage vocabularies"))
        self.vocab_edit.setPlaceholderText(_translate("MainWindow", "Name of vocabulary... (required)"))
import window.interface.resource.src_rc