# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_vocab_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(280, 280)
        Dialog.setMinimumSize(QtCore.QSize(280, 280))
        Dialog.setMaximumSize(QtCore.QSize(280, 280))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vocabs_list = QtWidgets.QListWidget(Dialog)
        self.vocabs_list.setStyleSheet("*{\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}")
        self.vocabs_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.vocabs_list.setObjectName("vocabs_list")
        self.verticalLayout.addWidget(self.vocabs_list)
        self.vocab_edit = QtWidgets.QLineEdit(Dialog)
        self.vocab_edit.setStyleSheet("")
        self.vocab_edit.setObjectName("vocab_edit")
        self.verticalLayout.addWidget(self.vocab_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setStyleSheet("*{\n"
"    image: url(:/add_icon/icons8-add-24.png);\n"
"}")
        self.create_button.setText("")
        self.create_button.setObjectName("create_button")
        self.horizontalLayout.addWidget(self.create_button)
        self.delete_button = QtWidgets.QPushButton(Dialog)
        self.delete_button.setStyleSheet("*{image: url(:/delete_icon/icons8-remove-24.png);}")
        self.delete_button.setText("")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.vocab_edit.setPlaceholderText(_translate("Dialog", "Name of vocabulary... (required)"))
        self.create_button.setShortcut(_translate("Dialog", "Ctrl+N"))
        self.delete_button.setShortcut(_translate("Dialog", "Del"))
import window.interface.resource.src_rc
