# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_vocab_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(280, 280)
        Dialog.setMinimumSize(QtCore.QSize(280, 280))
        Dialog.setMaximumSize(QtCore.QSize(280, 280))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vocab_list = QtWidgets.QListWidget(Dialog)
        self.vocab_list.setStyleSheet("*{\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"\n"
"")
        self.vocab_list.setObjectName("vocab_list")
        self.verticalLayout.addWidget(self.vocab_list)
        self.open_button = QtWidgets.QPushButton(Dialog)
        self.open_button.setStyleSheet("*{\n"
"    image: url(:/enter_icon/icons8-next-page-24.png);}")
        self.open_button.setText("")
        self.open_button.setObjectName("open_button")
        self.verticalLayout.addWidget(self.open_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
import window.interface.resource.src_rc
