# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(420, 120)
        Dialog.setMinimumSize(QtCore.QSize(420, 120))
        Dialog.setMaximumSize(QtCore.QSize(420, 120))
        Dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.accuracy_label = QtWidgets.QLabel(Dialog)
        self.accuracy_label.setStyleSheet("")
        self.accuracy_label.setObjectName("accuracy_label")
        self.horizontalLayout.addWidget(self.accuracy_label)
        self.accuracy_progressbar = QtWidgets.QProgressBar(Dialog)
        self.accuracy_progressbar.setStyleSheet("*{\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 16px;}")
        self.accuracy_progressbar.setProperty("value", 100)
        self.accuracy_progressbar.setTextVisible(True)
        self.accuracy_progressbar.setInvertedAppearance(False)
        self.accuracy_progressbar.setObjectName("accuracy_progressbar")
        self.horizontalLayout.addWidget(self.accuracy_progressbar)
        self.pts_label = QtWidgets.QLabel(Dialog)
        self.pts_label.setObjectName("pts_label")
        self.horizontalLayout.addWidget(self.pts_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.word_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.word_label.setFont(font)
        self.word_label.setTextFormat(QtCore.Qt.PlainText)
        self.word_label.setScaledContents(False)
        self.word_label.setAlignment(QtCore.Qt.AlignCenter)
        self.word_label.setWordWrap(False)
        self.word_label.setObjectName("word_label")
        self.verticalLayout.addWidget(self.word_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.statistic_button = QtWidgets.QPushButton(Dialog)
        self.statistic_button.setStyleSheet("*{image: url(:/statistic_icon/icons8-graph-24.png);}")
        self.statistic_button.setText("")
        self.statistic_button.setObjectName("statistic_button")
        self.horizontalLayout_2.addWidget(self.statistic_button)
        self.translation_edit = QtWidgets.QLineEdit(Dialog)
        self.translation_edit.setStyleSheet("*{\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      \n"
"}")
        self.translation_edit.setObjectName("translation_edit")
        self.horizontalLayout_2.addWidget(self.translation_edit)
        self.check_button = QtWidgets.QPushButton(Dialog)
        self.check_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.check_button.setStyleSheet("*{image: url(:/enter_icon/icons8-next-page-24.png);}")
        self.check_button.setText("")
        self.check_button.setObjectName("check_button")
        self.horizontalLayout_2.addWidget(self.check_button)
        self.check_button_2 = QtWidgets.QPushButton(Dialog)
        self.check_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.check_button_2.setStyleSheet("*{\n"
"    image: url(:/correct_icon/icons8-approval-24.png);\n"
"\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}")
        self.check_button_2.setText("")
        self.check_button_2.setObjectName("check_button_2")
        self.horizontalLayout_2.addWidget(self.check_button_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.accuracy_label.setText(_translate("Dialog", "Accuracy: "))
        self.pts_label.setText(_translate("Dialog", "Points: 0"))
        self.word_label.setText(_translate("Dialog", "Word"))
        self.statistic_button.setShortcut(_translate("Dialog", "Ctrl+S"))
        self.translation_edit.setPlaceholderText(_translate("Dialog", "Enter original word or translation..."))
        self.check_button.setShortcut(_translate("Dialog", "Return"))
import window.interface.resource.src_rc
