# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translate_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(420, 95)
        Dialog.setMinimumSize(QtCore.QSize(420, 95))
        Dialog.setMaximumSize(QtCore.QSize(420, 95))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.translate_to = QtWidgets.QComboBox(Dialog)
        self.translate_to.setStyleSheet("")
        self.translate_to.setObjectName("translate_to")
        self.horizontalLayout_2.addWidget(self.translate_to)
        self.output_edit = QtWidgets.QLineEdit(Dialog)
        self.output_edit.setStyleSheet("")
        self.output_edit.setReadOnly(True)
        self.output_edit.setObjectName("output_edit")
        self.horizontalLayout_2.addWidget(self.output_edit)
        self.translate_button = QtWidgets.QPushButton(Dialog)
        self.translate_button.setStyleSheet("*{\n"
"    image: url(:/translate_icon/icons8-translate-24.png);\n"
"}")
        self.translate_button.setText("")
        self.translate_button.setObjectName("translate_button")
        self.horizontalLayout_2.addWidget(self.translate_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.translate_from = QtWidgets.QComboBox(Dialog)
        self.translate_from.setStyleSheet("")
        self.translate_from.setObjectName("translate_from")
        self.horizontalLayout.addWidget(self.translate_from)
        self.phrase_edit = QtWidgets.QLineEdit(Dialog)
        self.phrase_edit.setStyleSheet("")
        self.phrase_edit.setText("")
        self.phrase_edit.setObjectName("phrase_edit")
        self.horizontalLayout.addWidget(self.phrase_edit)
        self.copy_button = QtWidgets.QPushButton(Dialog)
        self.copy_button.setStyleSheet("*{\n"
"    image: url(:/copy_icon/icons8-copy-24.png);\n"
"}")
        self.copy_button.setText("")
        self.copy_button.setObjectName("copy_button")
        self.horizontalLayout.addWidget(self.copy_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Translate to     "))
        self.translate_button.setShortcut(_translate("Dialog", "Return"))
        self.label.setText(_translate("Dialog", "Translate from"))
        self.phrase_edit.setPlaceholderText(_translate("Dialog", "Enter word or phrase..."))
        self.copy_button.setShortcut(_translate("Dialog", "Ctrl+C"))
import window.interface.resource.src_rc
