# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translate_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 90)
        MainWindow.setStyleSheet("background:  #323232;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.translate_from = QtWidgets.QComboBox(self.centralwidget)
        self.translate_from.setStyleSheet("*{\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}")
        self.translate_from.setObjectName("translate_from")
        self.horizontalLayout.addWidget(self.translate_from)
        self.phrase_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.phrase_edit.setStyleSheet("*{\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.phrase_edit.setText("")
        self.phrase_edit.setObjectName("phrase_edit")
        self.horizontalLayout.addWidget(self.phrase_edit)
        self.translate_button = QtWidgets.QPushButton(self.centralwidget)
        self.translate_button.setStyleSheet("*{\n"
"    image: url(:/translate_icon/icons8-translate-24.png);\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.translate_button.setText("")
        self.translate_button.setObjectName("translate_button")
        self.horizontalLayout.addWidget(self.translate_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.translate_to = QtWidgets.QComboBox(self.centralwidget)
        self.translate_to.setStyleSheet("*{\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"\\")
        self.translate_to.setObjectName("translate_to")
        self.horizontalLayout_2.addWidget(self.translate_to)
        self.output_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.output_edit.setStyleSheet("*{\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}")
        self.output_edit.setReadOnly(True)
        self.output_edit.setObjectName("output_edit")
        self.horizontalLayout_2.addWidget(self.output_edit)
        self.copy_button = QtWidgets.QPushButton(self.centralwidget)
        self.copy_button.setStyleSheet("*{image: url(:/copy_icon/icons8-copy-24.png);\n"
"background: #424242;\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"height: 32px;}\n"
"*:hover {\n"
"     height: 32px;\n"
"      border: 1px solid white;\n"
"      background: #626262;\n"
"}")
        self.copy_button.setText("")
        self.copy_button.setObjectName("copy_button")
        self.horizontalLayout_2.addWidget(self.copy_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Translate"))
        self.label.setText(_translate("MainWindow", "Translate from"))
        self.phrase_edit.setPlaceholderText(_translate("MainWindow", "Enter word or phrase..."))
        self.label_2.setText(_translate("MainWindow", "Translate to     "))
import window.interface.resource.src_rc
